version: "3"

services:
  backend:
    build: 
      context: .
      args:
        DEV: "true"
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app/
    container_name: fastapi-backend

  frontend:
    build: ./app/frontend
    ports:
      - "3000:3000"
    volumes:
      # - ./Caddyfile:/etc/caddy/Caddyfile
      # - caddy-data:/data
      # - caddy-config:/config
      - ./app/frontend/:/app/
    # depends_on:
    #   - backend
    stdin_open: true
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    container_name: react-frontend

# volumes:
#   caddy-data:
#   caddy-config: