version: "3"

services:
  backend:
    build: 
      context: .
      args:
        DEV: "true"
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app/

  frontend:
    build: ./app/frontend
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
      - ./app/frontend:/app/frontend
      - ./app/frontend/:/app/frontend/node_modules
    depends_on:
      - backend
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  caddy-data:
  caddy-config: